version: '3.1'

services:

  web:
    container_name: web
    build: 
      context: .
      dockerfile: ./src/Dockerfile
    depends_on: [ db ]
    ports:
      - "8080:80"
  db:
    image: mariadb:10.9.4
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: online_shop
    volumes:
      - db:/var/lib/mysql

volumes:
  db: