version: '3.1'

services:
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: online_shop
    volumes:
      - db:/var/lib/mysql

volumes:
  db: