version: '3.1'

services:

  web:
    container_name: web
    build: .
    image: m151onlineshop.azurecr.io/web
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:10.9.4
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root 
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: online_shop
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

volumes:
  db:
    driver: azure_file
    driver_opts:
      share_name: mym151fileshare
      storage_account_name: mym151storageaccount